import React from 'react'

const Terms_condition = () => {
    return (
        <div className="p-5">
            <div className="_1AtVbE col-12-12">
                <div className="_2Q9A4t">
                    <div className="p-5" style={{ boxShadow: "0px 0px 5px" }}>
                        <p>
                            <strong>Shopy Terms or Condition</strong>
                        </p>
                        <p>
                            <strong>
                                This document is an electronic record in terms of Information
                                Technology Act, 2000 and rules there under as applicable and the
                                amended provisions pertaining to electronic records in various
                                statutes as amended by the Information Technology Act, 2000. This
                                electronic record is generated by a computer system and does not
                                require any physical or digital signatures.
                            </strong>
                        </p>
                        <p>
                            <strong>
                                This document is published in accordance with the provisions of Rule
                                3 (1) of the Information Technology (Intermediaries guidelines)
                                Rules, 2011 that require publishing the rules and regulations,
                                privacy policy and Terms of Use for access or usage of domain name{" "}
                            </strong>
                            [<strong>www.Shopy.com</strong>][www.Shopy.com]{" "}
                            <strong>
                                (“Website”), including the related mobile site and mobile
                                application (hereinafter referred to as “Platform”){" "}
                            </strong>
                        </p>
                        <p>
                            The Platform is owned by Shopy Internet Private Limited a company
                            incorporated under the Companies Act, 1956 with its registered office
                            at Buildings Alyssa, Begonia &amp; Clover, Embassy Tech Village, Outer
                            Ring Road, Devarabeesanahalli Village, Bengaluru – 560103, Karnataka,
                            India and its branch offices at 2nd Floor, Block F (Flora), Embassy
                            Tech Village, Outer Ring Road, Devarabeesanahalli Village,
                            Bengaluru-560103, Karnataka, India and; 447/C, 12th Main, 4th Block,
                            Koramangala, Bengaluru-560034, Karnataka, India (hereinafter referred
                            to as "Shopy").
                        </p>
                        <p>
                            Your use of the Platform and services and tools are governed by the
                            following terms and conditions <strong>("Terms of Use")</strong> as
                            applicable to the Platform including the applicable policies which are
                            incorporated herein by way of reference. If You transact on the
                            Platform, You shall be subject to the policies that are applicable to
                            the Platform for such transaction. By mere use of the Platform, You
                            shall be contracting with Shopy Internet Private Limited and these
                            terms and conditions including the policies constitute Your binding
                            obligations, with Shopy.
                        </p>
                        <p>
                            For the purpose of these Terms of Use, wherever the context so
                            requires <strong>"You"</strong> or <strong>"User"</strong> shall mean
                            any natural or legal person who has agreed to become a buyer on the
                            Platform by providing Registration Data while registering on the
                            Platform as Registered User using the computer systems. Shopy
                            allows the User to surf the Platform or making purchases without
                            registering on the Platform. The term{" "}
                            <strong>"We", "Us", "Our"</strong> shall mean Shopy Internet
                            Private Limited.
                        </p>
                        <p>
                            When You use any of the services provided by Us through the Platform,
                            including but not limited to, (e.g. Product Reviews, Seller Reviews),
                            You will be subject to the rules, guidelines, policies, terms, and
                            conditions applicable to such service, and they shall be deemed to be
                            incorporated into this Terms of Use and shall be considered as part
                            and parcel of this Terms of Use. We reserve the right, at Our sole
                            discretion, to change, modify, add or remove portions of these Terms
                            of Use, at any time without any prior written notice to You. It is
                            Your responsibility to review these Terms of Use periodically for
                            updates / changes. Your continued use of the Platform following the
                            posting of changes will mean that You accept and agree to the
                            revisions. As long as You comply with these Terms of Use, We grant You
                            a personal, non-exclusive, non-transferable, limited privilege to
                            enter and use the Platform.
                        </p>
                        <p>
                            <strong>
                                ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR
                                AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE,
                                SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING
                            </strong>
                            . By impliedly or expressly accepting these Terms of Use, You also
                            accept and agree to be bound by Shopy Policies ((including but not
                            limited to Privacy Policy available at Privacy) as amended from time
                            to time.
                        </p>
                        <p>
                            <strong>Membership Eligibility</strong>
                        </p>
                        <p>
                            Transaction on the Platform is available only to persons who can form
                            legally binding contracts under Indian Contract Act, 1872. Persons who
                            are "incompetent to contract" within the meaning of the Indian
                            Contract Act, 1872 including un-discharged insolvents etc. are not
                            eligible to use the Platform. If you are a minor i.e. under the age of
                            18 years, you may use the Platform or access content on the Platform
                            only under the supervision and prior consent/ permission of a parent
                            ormlegal guardian.
                        </p>
                        <p>
                            As a minor if you wish to transact on the Platform, such transaction
                            on the Platform may be made by your legal guardian or parents.
                            Shopy reserves the right to terminate your membership and / or
                            refuse to provide you with access to the Platform if it is brought to
                            Shopy's notice or if it is discovered that You are under the age of
                            18 years and transacting on the Platform.
                        </p>
                        <p>
                            <strong>Your Account and Registration Obligations</strong>
                        </p>
                        <p>
                            If You use the Platform, You shall be responsible for maintaining the
                            confidentiality of your Display Name and Password and You shall be
                            responsible for all activities that occur under your Display Name and
                            Password. You agree that if You provide any information that is
                            untrue, inaccurate, not current or incomplete or We have reasonable
                            grounds to suspect that such information is untrue, inaccurate, not
                            current or incomplete, or not in accordance with the this Terms of
                            Use, We shall have the right to indefinitely suspend or terminate or
                            block access of your membership on the Platform and refuse to provide
                            You with access to the Platform.
                        </p>
                        <p>
                            Your mobile phone number and/or e-mail address is treated as Your
                            primary identifier on the Platform. It is your responsibility to
                            ensure that Your mobile phone number and your email address is up to
                            date on the Platform at all times. You agree to notify Us promptly if
                            your mobile phone number or e-mail address changes by updating the
                            same on the Platform through a onetime password verification.
                        </p>
                        <p>
                            You agree that Shopy shall not be liable or responsible for the
                            activities or consequences of use or misuse of any information that
                            occurs under your Account in cases, including, where You have failed
                            to update Your revised mobile phone number and/or e-mail address on
                            the Website Platform.
                        </p>
                        <p>
                            If You share or allow others to have access to Your account on the
                            Platform (“Account”), by creating separate profiles under Your
                            Account, or otherwise, they will be able to view and access Your
                            Account information. You shall be solely liable and responsible for
                            all the activities undertaken under Your Account, and any consequences
                            therefrom.
                        </p>
                        <p>
                            <strong>Communications</strong>
                        </p>
                        <p>
                            When You use the Platform or send emails or other data, information or
                            communication to us, You agree and understand that You are
                            communicating with Us through electronic records and You consent to
                            receive communications via electronic records from Us periodically and
                            as and when required. We may communicate with you by email or by such
                            other mode of communication, electronic or otherwise.
                        </p>
                        <p>
                            <strong>Platform for Transaction and Communication</strong>
                        </p>
                        <p>
                            The Platform is a platform that Users utilize to meet and interact
                            with one another for their transactions. Shopy is not and cannot be
                            a party to or control in any manner any transaction between the
                            Platform's Users.
                        </p>
                        <p>Henceforward:</p>
                        <ol>
                            <li>
                                All commercial/contractual terms are offered by and agreed to
                                between Buyers and Sellers alone. The commercial/contractual terms
                                include without limitation price, shipping costs, payment methods,
                                payment terms, date, period and mode of delivery, warranties related
                                to products and services and after sales services related to
                                products and services. Shopy does not have any control or does
                                not determine or advise or in any way involve itself in the offering
                                or acceptance of such commercial/contractual terms between the
                                Buyers and Sellers. All discounts, offers (including exchange
                                offers) are by the Seller/Brand and not by Shopy.
                            </li>
                            <li>
                                Placement of order by a Buyer with Seller on the Platform is an
                                offer to buy the product(s) in the order by the Buyer to the Seller
                                and it shall not be construed as Seller's acceptance of Buyer's
                                offer to buy the product(s) ordered. The Seller retains the right to
                                cancel any such order placed by the Buyer, at its sole discretion
                                and the Buyer shall be intimated of the same by way of an email/SMS.
                                Any transaction price paid by Buyer in case of such cancellation by
                                Seller, shall be refunded to the Buyer. Further, the Seller may
                                cancel an order wherein the quantities exceed the typical individual
                                consumption. This applies both to the number of products ordered
                                within a single order and the placing of several orders for the same
                                product where the individual orders comprise a quantity that exceeds
                                the typical individual consumption. What comprises a typical
                                individual's consumption quantity limit shall be based on various
                                factors and at the sole discretion of the Seller and may vary from
                                individual to individual.
                            </li>
                            <li>
                                Shopy does not make any representation or Warranty as to
                                specifics (such as quality, value, salability, etc) of the products
                                or services proposed to be sold or offered to be sold or purchased
                                on the Platform. Shopy does not implicitly or explicitly support
                                or endorse the sale or purchase of any products or services on the
                                Platform. Shopy accepts no liability for any errors or omissions,
                                whether on behalf of itself or third parties.
                            </li>
                            <li>
                                Shopy is not responsible for any non-performance or breach of any
                                contract entered into between Buyers and Sellers. Shopy cannot
                                and does not guarantee that the concerned Buyers and/or Sellers will
                                perform any transaction concluded on the Platform. Shopy shall
                                not and is not required to mediate or resolve any dispute or
                                disagreement between Buyers and Sellers.
                            </li>
                            <li>
                                Shopy does not make any representation or warranty as to the
                                item-specifics (such as legal title, creditworthiness, identity,
                                etc) of any of its Users. You are advised to independently verify
                                the bona fides of any particular User that You choose to deal with
                                on the Platform and use Your best judgment in that behalf.
                            </li>
                            <li>
                                Shopy does not at any point of time during any transaction
                                between Buyer and Seller on the Platform come into or take
                                possession of any of the products or services offered by Seller nor
                                does it at any point gain title to or have any rights or claims over
                                the products or services offered by Seller to Buyer.
                            </li>
                            <li>
                                At no time shall Shopy hold any right, title or interest over the
                                products nor shall Shopy have any obligations or liabilities in
                                respect of such contract entered into between Buyers and Sellers.
                                Shopy is not responsible for unsatisfactory or delayed
                                performance of services or damages or delays as a result of products
                                which are out of stock, unavailable or back ordered.
                            </li>
                            <li>
                                The Platform is only a platform that can be utilized by Users to
                                reach a larger base to buy and sell products or services. Shopy
                                is only providing a platform for communication and it is agreed that
                                the contract for sale of any of the products or services shall be a
                                strictly bipartite contract between the Seller and the Buyer.
                            </li>
                        </ol>
                        <p>
                            At no time shall Shopy hold any right, title or interest over the
                            products nor shall Shopy have any obligations or liabilities in
                            respect of such contract.
                        </p>
                        <p>
                            Shopy is not responsible for unsatisfactory or delayed performance
                            of services or damages or delays as a result of products which are out
                            of stock, unavailable or back ordered.
                        </p>
                        <p>
                            {" "}
                            Select products offered by sellers may be eligible for business
                            purchases on the Platform.
                        </p>
                        <ol>
                            <li>
                                <p>
                                    Upon Your purchase of product(s) eligible for business purchases,
                                    You may be able to avail the benefits of GST input tax credit.
                                    Accordingly, at your request, an invoice containing the GSTIN as
                                    provided by You ("Tax Invoice") shall be issued to You by the
                                    Seller(s) selling such products.
                                </p>
                                <ul>
                                    <li>
                                        GST invoice will have, inter alia, the following details printed
                                        on it: -GSTIN associated with your registered business, as
                                        provided by you
                                    </li>
                                    <li>
                                        Entity name of your registered business, as provided by you
                                    </li>
                                    <li>
                                        Not all products are eligible for business purchases on the
                                        Platform and the same is solely at the discretion of the
                                        Sellers. You will be able to view the eligibility of Tax Invoice
                                        on the product page on the Platform.
                                    </li>
                                    <li>
                                        Purchases on the Platform must only be for end consumption.
                                        Users must not use products purchased on the Platform for any
                                        commercial, promotional, resale or further distribution
                                        purposes.
                                    </li>
                                    <li>
                                        For seamless availment of input tax credit, kindly mention the
                                        delivery address as the address which is mentioned as the
                                        registered place of business as per the records of GST
                                        authority. Please note that availment of input tax credit is
                                        subject to provisions of GST Act and rules.{" "}
                                    </li>
                                    <li>
                                        The delivery and billing addresses will be required to be the
                                        same, please note that input tax credit will be denied by GST
                                        authority if the delivery address and GSTIN in the GST invoice
                                        are of different states.
                                    </li>
                                    <li>
                                        If GSTIN and/or business entity details are not provided by You,
                                        it will be presumed that it is a personal purchase and not a
                                        business purchase.
                                    </li>
                                    <li>
                                        Shopy is not responsible to verify the correctness of the
                                        GSTIN and/or entity name provided by You and You shall be
                                        entirely responsible to provide the accurate details.
                                    </li>
                                    <li>
                                        Shopy and Seller shall not entertain any request for any
                                        revision in the GST Invoice. Shopy and Seller shall not be
                                        liable for Your default including for reasons associated with
                                        details provided by You.
                                    </li>
                                    <li>
                                        Shopy will not be liable in case You are not able to avail
                                        input tax credit or if input tax credit is denied to You for any
                                        reason whatsoever.
                                    </li>
                                    <li>
                                        You shall be solely liable for all compliances required under
                                        applicable laws.
                                    </li>
                                    <li>
                                        You agree to indemnify and hold Shopy and Seller harmless
                                        from all losses, claims, costs, expenses, suits, proceedings, or
                                        any other liability including any third-party claims (including
                                        any penalties imposed by governmental authorities) arising out
                                        of or in connection with (1) the GSTIN and/or entity name
                                        provided by you or the input tax credit claimed by you or your
                                        use or misuse of the GST Invoice and (2) your non-compliance
                                        with the applicable laws or (3) your use or misuse of any
                                        third-party’s details including GSTIN.
                                    </li>
                                    <li>
                                        Shopy has the right to not allow business purchases on the
                                        Platform to You if a fraudulent activity is identified.
                                    </li>
                                    <li>
                                        Seller reserves the right to not issue Tax Invoice or issue a
                                        credit note against an already issued Tax Invoice to cancel the
                                        transaction, if any fraudulent activity is identified.
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <p>
                                    You shall independently agree upon the manner and terms and
                                    conditions of delivery, payment, insurance etc. with the seller(s)
                                    that You transact with.
                                </p>
                            </li>
                        </ol>
                        <p>
                            Disclaimer: Pricing on any product(s) as is reflected on the Platform
                            may due to some technical issue, typographical error or product
                            information published by seller may be incorrectly reflected and in
                            such an event seller may cancel such your order(s).
                        </p>
                        <ol>
                            <li>
                                You release and indemnify Shopy and/or any of its officers and
                                representatives from any cost, damage, liability or other
                                consequence of any of the actions of the Users of the Platform and
                                specifically waive any claims that you may have in this behalf under
                                any applicable law. Notwithstanding its reasonable efforts in that
                                behalf, Shopy cannot take responsibility or control the
                                information provided by other Users which is made available on the
                                Platform. You may find other User's information to be offensive,
                                harmful, inconsistent, inaccurate, or deceptive. Please use caution
                                and practice safe trading when using the Platform.
                            </li>
                        </ol>
                        <p>
                            Please note that there could be risks in dealing with underage persons
                            or people acting under false pretence.
                        </p>
                        <p>
                            <strong>Charges</strong>
                        </p>
                        <p>
                            Shopy may charge a nominal fee for browsing and buying on the
                            Platform. Shopy reserves the right to change its Fee Policy from
                            time to time. In particular, Shopy may at its sole discretion
                            introduce new services/fees and modify some or all of the existing
                            services/fees offered on the Platform. In such an event, Shopy
                            reserves the right to introduce fees for the new services offered or
                            amend/introduce fees for existing/new services, as the case may be.
                            Changes to the Fee Policy shall be posted on the Platform and such
                            changes shall automatically become effective immediately after they
                            are posted on the Platform. Unless otherwise stated, all fees shall be
                            quoted in Indian Rupees. You shall be solely responsible for
                            compliance of all applicable laws including those in India for making
                            payments to Shopy Internet Private Limited
                        </p>
                        <p>
                            <strong>Use of the Platform</strong>
                        </p>
                        <p>
                            You agree, undertake and confirm that Your use of Platform shall be
                            strictly governed by the following binding principles:
                        </p>
                        <ol>
                            <li>
                                You shall not host, display, upload, modify, publish, transmit,
                                update or share any information which:
                            </li>
                        </ol>
                        <p>
                            (a) belongs to another person and to which You does not have any right
                            to;
                        </p>
                        <p>
                            (b) is grossly harmful, harassing, blasphemous, defamatory, obscene,
                            pornographic, paedophilic, libellous, invasive of another's privacy,
                            hateful, or racially, ethnically objectionable, disparaging, relating
                            or encouraging money laundering or gambling, or otherwise unlawful in
                            any manner whatever; or unlawfully threatening or unlawfully harassing
                            including but not limited to "indecent representation of women" within
                            the meaning of the Indecent Representation of Women (Prohibition) Act,
                            1986;
                        </p>
                        <p>(c) is misleading in any way;</p>
                        <p>
                            (d) is patently offensive to the online community, such as sexually
                            explicit content, or content that promotes obscenity, paedophilia,
                            racism, bigotry, hatred or physical harm of any kind against any group
                            or individual;
                        </p>
                        <p>(e) harasses or advocates harassment of another person;</p>
                        <p>
                            (f) involves the transmission of "junk mail", "chain letters", or
                            unsolicited mass mailing or "spamming";
                        </p>
                        <p>
                            (g) promotes illegal activities or conduct that is abusive,
                            threatening, obscene, defamatory or libellous;
                        </p>
                        <p>
                            (h) infringes upon or violates any third party's rights [including,
                            but not limited to, intellectual property rights, rights of privacy
                            (including without limitation unauthorized disclosure of a person's
                            name, email address, physical address or phone number) or rights of
                            publicity];
                        </p>
                        <p>
                            (i) promotes an illegal or unauthorized copy of another person's
                            copyrighted work (see "Copyright complaint" below for instructions on
                            how to lodge a complaint about uploaded copyrighted material), such as
                            providing pirated computer programs or links to them, providing
                            information to circumvent manufacture-installed copy-protect devices,
                            or providing pirated music or links to pirated music files;
                        </p>
                        <p>
                            (j) contains restricted or password-only access pages, or hidden pages
                            or images (those not linked to or from another accessible page);
                        </p>
                        <p>
                            (k) provides material that exploits people in a sexual, violent or
                            otherwise inappropriate manner or solicits personal information from
                            anyone;
                        </p>
                        <p>
                            (l) provides instructional information about illegal activities such
                            as making or buying illegal weapons, violating someone's privacy, or
                            providing or creating computer viruses;
                        </p>
                        <p>
                            (m) contains video, photographs, or images of another person (with a
                            minor or an adult).
                        </p>
                        <p>
                            (n) tries to gain unauthorized access or exceeds the scope of
                            authorized access to the Platform or to profiles, blogs, communities,
                            account information, bulletins, friend request, or other areas of the
                            Platform or solicits passwords or personal identifying information for
                            commercial or unlawful purposes from other users;
                        </p>
                        <p>
                            (o) engages in commercial activities and/or sales without Our prior
                            written consent such as contests, sweepstakes, barter, advertising and
                            pyramid schemes, or the buying or selling of "virtual" products
                            related to the Platform. Throughout this Terms of Use, Shopy's
                            prior written consent means a communication coming from Shopy's
                            Legal Department, specifically in response to Your request, and
                            specifically addressing the activity or conduct for which You seek
                            authorization;
                        </p>
                        <p>
                            (p) solicits gambling or engages in any gambling activity which We, in
                            Our sole discretion, believes is or could be construed as being
                            illegal;
                        </p>
                        <p>
                            (q) interferes with another USER's use and enjoyment of the Platform
                            or any other individual's User and enjoyment of similar services;
                        </p>
                        <p>
                            (r) refers to any Platform or URL that, in Our sole discretion,
                            contains material that is inappropriate for the Platform or any other
                            Platform, contains content that would be prohibited or violates the
                            letter or spirit of these Terms of Use.
                        </p>
                        <p>(s) harm minors in any way;</p>
                        <p>
                            (t) infringes any patent, trademark, copyright or other proprietary
                            rights or third party's trade secrets or rights of publicity or
                            privacy or shall not be fraudulent or involve the sale of counterfeit
                            or stolen products;
                        </p>
                        <p>(u) violates any law for the time being in force;</p>
                        <p>
                            (v) deceives or misleads the addressee/ users about the origin of such
                            messages or communicates any information which is grossly offensive or
                            menacing in nature;
                        </p>
                        <p>(w) impersonate another person;</p>
                        <p>
                            (x) contains software viruses or any other computer code, files or
                            programs designed to interrupt, destroy or limit the functionality of
                            any computer resource; or contains any trojan horses, worms, time
                            bombs, cancelbots, easter eggs or other computer programming routines
                            that may damage, detrimentally interfere with, diminish value of,
                            surreptitiously intercept or expropriate any system, data or personal
                            information;
                        </p>
                        <p>
                            (y) threatens the unity, integrity, defence, security or sovereignty
                            of India, friendly relations with foreign states, or public order or
                            causes incitement to the commission of any cognizable offence or
                            prevents investigation of any offence or is insulting any other
                            nation.
                        </p>
                        <p>(z) shall not be false, inaccurate or misleading;</p>
                        <p>
                            (aa) shall not, directly or indirectly, offer, attempt to offer, trade
                            or attempt to trade in any item, the dealing of which is prohibited or
                            restricted in any manner under the provisions of any applicable law,
                            rule, regulation or guideline for the time being in force.
                        </p>
                        <p>
                            (ab) shall not create liability for Us or cause Us to lose (in whole
                            or in part) the services of Our internet service provider ("ISPs") or
                            other suppliers;
                        </p>
                    </div>
                </div>
            </div>
        </div>

    )
}

export default Terms_condition
